Comment IOs part in github workflow

diff --git a/.github/workflows/flutter.yml b/.github/workflows/flutter.yml
--- a/.github/workflows/flutter.yml
+++ b/.github/workflows/flutter.yml
@@ -231,69 +231,69 @@ jobs:
           name: backend_${{ github.job }}.log
           path: backend/backend.log
           
-  frontend-ios-integration-test:
-    needs: frontend-setup
-    #Create a construction matrix
-    strategy:
-      #Set up different configurations for a set of virtual environments
-      matrix:
-        device:
-          - "iPhone 8 Simulator"
-      #When set to true, GitHub cancels all in progress jobs if any of the matrix jobs fail.
-      fail-fast: false
-    runs-on: macos-latest
-    steps:
-      - uses: actions/checkout@v2
+#  frontend-ios-integration-test:
+#    needs: frontend-setup
+#    #Create a construction matrix
+#    strategy:
+#      #Set up different configurations for a set of virtual environments
+#      matrix:
+#        device:
+#          - "iPhone 8 Simulator"
+#      #When set to true, GitHub cancels all in progress jobs if any of the matrix jobs fail.
+#      fail-fast: false
+#    runs-on: macos-latest
+#    steps:
+#      - uses: actions/checkout@v2
 
-      # Start Emulator
-      - name: "List all simulators"
-        run: "xcrun xctrace list devices"
-      - name: "Start Simulator"
-        run: |
-          UDID=$(xcrun xctrace list devices | grep "^${{ matrix.device }}" | awk '{gsub(/[()]/,""); print $NF}')
-          echo $UDID
-          xcrun simctl boot "${UDID:?No Simulator with this name found}"
+#      # Start Emulator
+#      - name: "List all simulators"
+#        run: "xcrun xctrace list devices"
+#      - name: "Start Simulator"
+#        run: |
+#          UDID=$(xcrun xctrace list devices | grep "^${{ matrix.device }}" | awk '{gsub(/[()]/,""); print $NF}')
+#          echo $UDID
+#          xcrun simctl boot "${UDID:?No Simulator with this name found}"
 
-      # Cache Flutter Environment
-      - name: Cache Flutter
-        id: cache-flutter
-        uses: actions/cache@v3
-        with:
-          path: /Users/runner/hostedtoolcache/flutter
-          key: ${{ runner.os }}-flutter
-      - uses: subosito/flutter-action@v2
-        with:
-          channel: 'stable'
-          
-      # Build 
-      - name: "Build Ipa"
-        run: |
-          ls
-          ls ios/
-          flutter build ios --simulator --target=integration_test/tests/credentials_test.dart || true 
-          ls ios/
-          cat ios/Podfile 
-        working-directory: ./frontend
+#      # Cache Flutter Environment
+#      - name: Cache Flutter
+#        id: cache-flutter
+#        uses: actions/cache@v3
+#        with:
+#          path: /Users/runner/hostedtoolcache/flutter
+#          key: ${{ runner.os }}-flutter
+#      - uses: subosito/flutter-action@v2
+#        with:
+#          channel: 'stable'
+#          
+#      # Build 
+#      - name: "Build Ipa"
+#        run: |
+#          ls
+#          ls ios/
+#          flutter build ios --simulator --target=integration_test/tests/credentials_test.dart || true 
+#          ls ios/
+#          cat ios/Podfile 
+#        working-directory: ./frontend
 
-      # Setup Server
-      - name: Install Server
-        uses: ./.github/actions/install-server-action
-      - name: Start Server
-        working-directory: ./backend
-        env:
-          CREDENTIALS_FOLDER: ${{ github.workspace }}/fake_credentials
-        run: |
-          mongoimport --jsonArray --db myapp --collection cottages --file ../frontend/assets/cottages.json
-          ((DEV=1 node ./app/index.js) &> backend.log) &
+#      # Setup Server
+#      - name: Install Server
+#        uses: ./.github/actions/install-server-action
+#      - name: Start Server
+#        working-directory: ./backend
+#        env:
+#          CREDENTIALS_FOLDER: ${{ github.workspace }}/fake_credentials
+#        run: |
+#          mongoimport --jsonArray --db myapp --collection cottages --file ../frontend/assets/cottages.json
+#          ((DEV=1 node ./app/index.js) &> backend.log) &
 
-      # Launch tests
-      - name: "Run Flutter Driver tests"
-        run: flutter test integration_test/tests --dart-define=BASE_URL=http://localhost:3000/api --dart-define=FIREBASE_ENABLED=false
-        working-directory: ./frontend
+#      # Launch tests
+#      - name: "Run Flutter Driver tests"
+#        run: flutter test integration_test/tests --dart-define=BASE_URL=http://localhost:3000/api --dart-define=FIREBASE_ENABLED=false
+#        working-directory: ./frontend
 
-      #Upload Artifacts
-      - uses: actions/upload-artifact@v1
-        if: always()
-        with:
-          name: backend_${{ github.job }}.log
-          path: backend/backend.log
+#      #Upload Artifacts
+#      - uses: actions/upload-artifact@v1
+#        if: always()
+#        with:
+#          name: backend_${{ github.job }}.log
+#          path: backend/backend.log
